# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
general:
  branches:
    ignore:
      - gh-pages

jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

  test:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run: curl -v -H "X-Storage-User: test:tester" -H "X-Storage-Pass: testing" http://127.0.0.1:8080/auth/v1.0
      - run: swift -A http://127.0.0.1:8080/auth/v1.0 -U test:tester -K testing stat
      - run: cp tests/test.config.circle-ci.js tests/test.config.js
      - run: npm install
      - run: npm test

workflows:
  version: 2
  test_build:
    jobs:
      - build
      - test